apiVersion: v1
kind: Pod
metadata:
  name: test-jenkins
spec:
  containers:
  - name: test-jenkins
    image: ryandenardis/test_jenkins:latest
    volumeMounts:
    - name: jenkins-data
      mountPath: /data/jenkins
  volumes:
  - name: jenkins-data
    emptyDir: {}
